
module Commercial_Activities_Contract where
import Land_info


-- 5. Commercial Activities Contract
commercialActivitiesContract :: String -> IO ()
commercialActivitiesContract escrowWallet = do
    putStrLn "Enter type of activity:"
    activityType <- getLine
    putStrLn "Enter name of activity:"
    activityName <- getLine
    putStrLn "Enter income generated by this activity:"
    income <- getLine
    putStrLn "Escrow wallet holder, choose your option:"
    putStrLn "1. Yes, Confirm Activity"
    putStrLn "2. Need Improvement"
    choice <- getLine
    case choice of
        "1" -> do
            putStrLn "Recording commercial activity details on the blockchain..."
            putStrLn $ "Type of activity: " ++ activityType
            putStrLn $ "Name of activity: " ++ activityName
            putStrLn $ "Income generated: " ++ income
            putStrLn $ "Transferring income to escrow wallet address: " ++ escrowWallet
            putStrLn "Confirmation of commercial activity. Income transferred."
        "2" -> putStrLn "Cancellation of commercial activity."
        _   -> putStrLn "Invalid choice!"